### ISSUE TITLE
Installing SSM Agent on Managed Instance can assign unreachable IP address

### ISSUE THREAD

**Issue by rewbotV86** [aws/amazon-ssm-agent#75] opened 2017-10-11 16:44 UTC
I’m using the Go SDK SSM `DescribeInstanceInformation` call to grab server information from a managed instance. I’m attempting to use the IP address retrieved from that call to query a database on that server. The problem is that the IP address stored for that server when SSM was installed is an address that is not reachable. It appears that the SSM client at installation queries the network stack for the status and attributes of the network adapters and, using the hardware id order, goes through each and associates the first valid ipv4 address to be the associated IP address for that host. On the server I’m using, the lowest numbered adapter is connected to a SAN that is not routable and so the SSM client is reporting that IP address as the IP address for the server.

Can a managed instance IP address be updated after SSM has been installed? Or, is it possible to assign a desired IP address to a managed instance when installing the SSM client?

**Comment by mmendonca3** [comment] 2018-02-06 21:57
Hello rewbotV86, 

we re currently investigating this issue and will hopefully have a fix soon. In the meanwhile, I will be closing this issue since it is a dupe of #27

**Closed by mmendonca3** 2018-02-06 21:57 UTC
