### ISSUE TITLE
'us-east-1':       AMI: 'ami-0323c3dd2da7fb37d' Failed to execute operation: File exists error

### ISSUE THREAD

**Issue by ismailyenigul** [aws/amazon-ssm-agent#282] opened 2020-05-20 00:25 UTC
Hello,
I am trying to deploy this Cloudformation stack 
https://github.com/widdix/aws-cf-templates/blob/master/wordpress/wordpress-ha.yaml
and it fails with the following error.

What could be wrong with  amazon-ssm-agent.service service?
I had to disable by setting false  HasSystemsManagerAccess parameter to run this stack successfully.  I made an ssh connection to the instance after disabling ssm deployment.
I could stop/start service without any issue.

```
20-05-19 22:02:02,386 [DEBUG] Using service modifier: /sbin/chkconfig
2020-05-19 22:02:02,386 [DEBUG] Setting service amazon-ssm-agent to enabled
2020-05-19 22:02:02,391 [ERROR] chkconfig failed with error 1. Output: Note: Forwarding request to 'systemctl enable amazon-ssm-agent.service'.
Failed to execute operation: File exists

2020-05-19 22:02:02,392 [ERROR] Error encountered during build of config: Could not enable service amazon-ssm-agent (return code 1)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 270, in build
    CloudFormationCarpenter._serviceTools[manager]().apply(services, changes)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 155, in apply
    self._set_service_enabled(service, util.interpret_boolean(serviceProperties["enabled"]))
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 234, in _set_service_enabled
    modifier.set_service_enabled(service, enabled);
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 297, in set_service_enabled
    raise ToolError("Could not %s service %s" % ("enable" if enabled else "disable", service), result.returncode)
ToolError: Could not enable service amazon-ssm-agent (return code 1)
2020-05-19 22:02:02,394 [ERROR] -----------------------BUILD FAILED!------------------------
2020-05-19 22:02:02,394 [ERROR] Unhandled exception during build: Could not enable service amazon-ssm-agent (return code 1)
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 270, in build
    CloudFormationCarpenter._serviceTools[manager]().apply(services, changes)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 155, in apply
    self._set_service_enabled(service, util.interpret_boolean(serviceProperties["enabled"]))
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 234, in _set_service_enabled
    modifier.set_service_enabled(service, enabled);
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 297, in set_service_enabled
    raise ToolError("Could not %s service %s" % ("enable" if enabled else "disable", service), result.returncode)
ToolError: Could not enable service amazon-ssm-agent (return code 1)
2020-05-19 22:02:02,653 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2020-05-19 22:02:02,654 [DEBUG] Signaling resource AutoScalingGroup in stack wordpress with unique ID i-xxx and status FAILURE
May 19 22:02:02 cloud-init[2670]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
May 19 22:02:02 cloud-init[2670]: util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Traceback (most recent call last):
  File "/usr/lib/pyt

```

**Comment by shihuazhang** [comment] 2020-05-26 18:46
Thanks for reaching out.

It looks like systemD related, may I know what is the OS and the version?

**Comment by ismailyenigul** [comment] 2020-05-26 19:16
Hi,
I believe it is amazon linux provisioned from https://github.com/widdix/aws-cf-templates/blob/master/wordpress/wordpress-ha.yaml

**Comment by shihuazhang** [comment] 2020-05-26 19:48
AL doesn't have systemD, AL does

**Comment by ismailyenigul** [comment] 2020-05-26 19:49
Yes it is Amazon Linux 2

**Comment by shihuazhang** [comment] 2020-05-26 20:14
tried with latest AL2, confirmed I can enable the amazon-ssm-agent without any error.

@ismailyenigul  is this something you could reach out to the original author?

**Comment by ismailyenigul** [comment] 2020-05-26 20:21
ok I will contact with the author. Did you try to deploy the stack yourself?

Thanks

**Comment by shihuazhang** [comment] 2020-05-27 02:33
I have not try the stack. The agent is installed/enabled on AL/AL2 by default now, you do not need to install the agent.

The Cloudformation might be outdated. I will close the issue, feel free to reopen it if you have more questions.

**Closed by shihuazhang** 2020-05-27 02:33 UTC
