### ISSUE TITLE
RunCommand output not written to regional S3 buckets

### ISSUE THREAD

**Issue by aidansteele** [aws/amazon-ssm-agent#25] opened 2016-11-03 00:00 UTC
When I specify an output S3 bucket, the output is not being saved if that bucket is in ap-southeast-2. It **does** work for buckets in us-east-1. Details that might be useful:

* AMI: ami-f4774a97
* Instance profile IAM role has managed policy attached with ARN `arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM`
* Successful command (bucket in us-east-1): `eddf140f-ee59-4fcd-a241-2fae11a931ae`
* Failing command (bucket in ap-southeast-2): `4a6afcf4-e344-47b0-9f54-aeba1baa9053`

Let me know if you require further information :)

**Comment by chanjeon** [comment] 2016-11-03 01:23
@aidansteele Thank you for the comment. 

Here are a few scenarios I can think of. 

1. Is the bucket in ap-southeast-2 named with dot(s)?
  Currently, SSMAgent can't upload output to bucket that has dot(s) in its name.

2. Did a folder named with command id created in bucket although output is not there?
     Please check if the command output is empty. SSMAgent creates a directory named with command id (also instance id under command id directory), but doesn't create plugin directory that contains the actual output if it is empty.

3. Did the command fail when you set the bucket to ap-southeast-2?
If the command failed, you can check the SSM log to find more details.

If none of them were scenarios that you ran into, could you share which region your instance was running. I can assist you further from there.

**Comment by aidansteele** [comment] 2016-11-03 02:03
* The instance was running in ap-southeast-2 for both tests (and is still running if you would like me to try diagnostics). 
* The bucket was named `aidan-test-ssm` (in ap-southeast-2) and `aidan-test-ssm-east` in us-east-1. 
* When viewing the Sydney bucket, the bucket was completely empty. 
* The EC2 SSM console shows the truncated output of the command, even when the full output isn't sent to S3.
* The command is just `ls` in Powershell and succeeds. How do I check the SSM log on Windows 2016?

**Comment by chanjeon** [comment] 2016-11-03 02:29
No problem!

I launched a 2016 instance in ap-southeast-2 and successfully sent the output to a bucket in the same region. I think the next step would be checking the SSM logs. They can be found in `C:\ProgramData\Amazon\SSM\Logs` in your instance. There are two logs called `amazon-ssm-agent.log` and `errors.log`. You can send the command again with the bucket name and check the `amazon-ssm-agent.log`. 

Please check if you can find a line similar to the following:
`uploading a test file to s3 bucket - <bucket name> , s3 key - <command id>/<instance id>/awsrunPowerShellScript with S3Client using region endpoint - ap-southeast-2
`

Please verify that it has the correct bucket name and the region. 

To get more logs, you can rename `C:\Program Files\Amazon\SSM\seelog.xml.template` to `C:\Program Files\Amazon\SSM\seelog.xml`, set `minLevel` (set to `info` by default) to `debug` and specify locations to save the logs. You need to restart SSMAgent service.

Please attach error logs here if you find anything related to uploading outputs to bucket.

**Comment by aidansteele** [comment] 2016-11-03 02:46
Thanks again. I've attached the complete `amazon-ssm-agent.log` for your perusal. Some lines that look relevant to me:


> 2016-11-02 23:28:46 INFO [instanceID=i-e7c806fc] [MessageProcessor] [pluginID=aws:runPowerShellScript] uploading logs to S3 with client configured to use region - us-east-1
2016-11-02 23:28:51 ERROR [instanceID=i-e7c806fc] [MessageProcessor] [pluginID=aws:runPowerShellScript] failed uploading C:\ProgramData\Amazon\SSM\InstanceData\i-e7c806fc\document\0a423991-b7dd-418d-b6da-89bd4a4e7f94\awsrunPowerShellScript\0.awsrunPowerShellScript\stdout to s3://aidan-test-ssm/moo/0a423991-b7dd-418d-b6da-89bd4a4e7f94/i-e7c806fc/awsrunPowerShellScript/0.awsrunPowerShellScript/stdout err:TemporaryRedirect: Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.
	status code: 307, request id: 223CD5F12AD9E759


[amazon-ssm-agent.log.zip](https://github.com/aws/amazon-ssm-agent/files/568139/amazon-ssm-agent.log.zip)

The `aidan-test-ssm` is in ap-southeast-2. Why would it decide to use us-east-1 endpoint? If it's any help, I _think_ I might have attached the IAM managed policy after instance boot.

**Comment by chanjeon** [comment] 2016-11-03 04:03
I am sorry, I didn't mean the full log. I don't think it's a good idea to attach the full log here. But it looks like your bucket is not created in ap-southeast-2. Could you verify your bucket is in the correct region? You can right click on the bucket and click properties. There should be Region field.

**Comment by aidansteele** [comment] 2016-11-03 05:22
Good point regarding the logs. I've removed it now. The bucket does appear to be in ap-southeast-2, attached a screenshot:

<img width="342" alt="screen shot 2016-11-03 at 4 21 26 pm" src="https://cloud.githubusercontent.com/assets/369053/19956513/ac91ccca-a1e1-11e6-9b26-1fdee6afbafc.png">

**Comment by chanjeon** [comment] 2016-11-03 07:14
If bucket is in the correct region, the high chance is that your instance has no permission to upload to s3 in ap-southeast-2. SSMAgent always uploads a test file prior to actual output to ensure it works with no permission issue or wrong bucket region and it sets the region to us-east-1 if  the test upload fails. It looks like that's why the instance uploads outputs to the default region. If you enable debug in seelog.xml as I explained in one of my previous comments, you can find the exact reason in log. Please let me know if you need help on this.

Also, as you mentioned, attaching/detaching the IAM policy after instance boot can cause an issue with permission. If it is verified to be the permission issue, I'd suggest you to re-launch an instance with IAM role attached with SSM managed policies. More detail: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/delegate-commands.html#ssm-managed-policies

**Comment by yayugu** [comment] 2017-01-10 07:31
I encountered the same problem with ap-sourtheast-1. I've runnning ssm-agent and createting S3 bucket on this region.
When I changed bucket on us-east-1, it works.

Using cli command like `aws s3 cp foo s3://...` works with buckets on any region. So I think It's not IAM issue.

**Comment by shihuazhang** [comment] 2017-01-19 19:37
It's not an IAM issue, the issue is caused by bucket name contains special characters such as '.' or '-'
The team is aware of the issue and they will work on the fixes soon

**Comment by jeremyye10** [comment] 2017-02-20 06:04
I've got same issue, but this issue was solved automatically after an hour.
I think s3 virtual hosting is related to this issue.
Please see the `Note` section from the below document.
http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

**Comment by gomker** [comment] 2017-05-02 20:23
I am seeing the same issue however, for some reason my Windows server works and Linux does not

Code:
```
      resp = self._ssm.send_command(InstanceIds=[instance_id],
                                      DocumentName=self._ssm_document,
                                      TimeoutSeconds=60,
                                      Parameters={'commands': [cmd]},
                                      OutputS3BucketName=self.s3_output_bucket,
                                      OutputS3Region=self.s3_bucket_region)
```
Output from SSM Agent from respective servers shows a completely different URI for the bucket

Windows 2012    : `https://s3.amazonaws.com/<mybucketname>/`
Linux RHEL 7.3  : `http://<mybucketname>.s3-us-west-2.amazonaws.com`

SSM Agent versions:
 Windows 2.0.533.0
 Linux : 2.0.761.0-1

**Comment by chanjeon** [comment] 2017-05-30 22:15
@yayugu and @gomker, Could you try to update the agent in your Windows instance? We've fixed a couple issues with s3 upload before and it's possible the issue has been fixed.

**Comment by yayugu** [comment] 2017-05-31 06:36
@chanjeon 

After I upgraded SSM Agent, everything works correctly!!
Thanks 🎉 

SSM Agent: 2.0.790.0
OS: Linux Ubuntu 14.04
Bucket Region: eu-central-1

**Comment by chanjeon** [comment] 2017-06-02 21:08
@yayugu Great! It looks like there are multiple issues mentioned for s3 upload in this issue and at least two of them are resolved by updating the agent. Please create a new issue with details if you still have a problem with s3 upload. Closing this issue.

**Closed by chanjeon** 2017-06-02 21:08 UTC

**Comment by giridhar82** [comment] 2018-07-23 09:37
I have the same issue.
ssm-Agent -2.2.800.0
Linux version -Linux version 4.14.47-64.38.amzn2.x86_64
Bucket region :us-east-1

Below is the output from ssm-agent.log.
2018-07-23 09:13:11 INFO [instanceID=i-040265df7863aa801] [MessagingDeliveryService] Sending reply {
  "additionalInfo": {
    "agent": {
      "lang": "en-US",
      "name": "amazon-ssm-agent",
      "os": "",
      "osver": "1",
      "ver": ""
    },
    "dateTime": "2018-07-23T09:13:11.543Z",
    "runId": "",
    "runtimeStatusCounts": {
      "Success": 1
    }
  },
  "documentStatus": "Success",
  "documentTraceOutput": "",
  "runtimeStatus": {
    "aws:runShellScript": {
      "status": "Success",
      "code": 0,
      "name": "aws:runShellScript",
      "output": "",
      "startDateTime": "2018-07-23T09:13:11.433Z",
      "endDateTime": "2018-07-23T09:13:11.438Z",
      "outputS3BucketName": "versioncheckfromssm",
      "outputS3KeyPrefix": "testxyz/f8794838-cc4f-4f3f-a9ea-d3ff27d72c0d/i-040265df7863aa801/awsrunShellScript",
      "standardOutput": "",
      "standardError": ""
    }
  }
}
2018-07-23 09:13:11 INFO [instanceID=i-040265df7863aa801] [MessagingDeliveryService] [EngineProcessor] execution of aws.ssm.f8794838-cc4f-4f3f-a9ea-d3ff27d72c0d.i-040265df7863aa801 is over. Removing interimState from current folder
2018-07-23 09:13:11 INFO [instanceID=i-040265df7863aa801] [MessagingDeliveryService] SendReply Response{
  Description: "Reply 8a3d846e-9fc3-4513-8405-df1b4d4bbf85 was successfully sent.",
  MessageId: "aws.ssm.f8794838-cc4f-4f3f-a9ea-d3ff27d72c0d.i-040265df7863aa801",
  ReplyId: "8a3d846e-9fc3-4513-8405-df1b4d4bbf85",
  ReplyStatus: "QUEUED"
}

But strange thing is , when there is an error, it is creating std.err in bucket.
