### ISSUE TITLE
`aws ssm start-session` for on-premise installations

### ISSUE THREAD

**Issue by kellertobias** [aws/amazon-ssm-agent#162] opened 2019-01-25 15:33 UTC
We are using the Systems Manager for Managing our Servers as well as the EC2 ones as also the few we have in our Office.

It would be great to be able to also use the session manager to connect to these servers.

**Comment by martenjacobs** [comment] 2019-02-11 11:09
+1

**Comment by caladfelipe** [comment] 2019-02-13 02:44
@kellertobias it is now available through [Session Manager](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html). Follow the [Getting started](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started.html)

**Comment by kouak** [comment] 2019-02-13 21:37
@caladfelipe Documentation clearly states that Session Manager does not support on-prem instances:
> **Note**
> 
> Session Manager supports Amazon EC2 instances only. On-premises instances are not supported at this time. 

`aws ssm start-session --target <on-prem-instance-id>` returns a BadRequest.

**Comment by msegzda** [comment] 2019-02-22 08:00
Definitely a much needed feature. Anxiously waiting when its rolled out. Seeing AWS working on it according to this blog post: https://aws.amazon.com/blogs/aws/new-session-manager/

**Comment by prasak-amzn** [comment] 2019-03-08 22:34
Session Manager is now supported for on premise instances. Check out the release notes here - [AWS - What's new](https://aws.amazon.com/about-aws/whats-new/2019/03/AWS_Systems_Manager_on-premises_instance_management_for_large_hybrid_environments/).

**Comment by BenPerel** [comment] 2019-03-22 19:15
@prasak-amzn Might want to update the public docs. As @kouak said, https://docs.aws.amazon.com/systems-manager/latest/userguide/what-is-session-manager.html still states the following:

"Session Manager lets you establish secure connections to your Amazon Elastic Compute Cloud (Amazon EC2) instances. **On-premises instances are not supported at this time**"

Glad to see the feature is out, thanks!

**Comment by omieomye** [comment] 2019-04-08 22:03
@BenPerel The public doc link you mentioned (https://docs.aws.amazon.com/systems-manager/latest/userguide/what-is-session-manager.html) is now accurate.  Thanks for the callout.

**Comment by hiimtu** [comment] 2019-05-29 22:32
Closing issue as on-prem session manager is now supported.

**Closed by hiimtu** 2019-05-29 22:32 UTC

**Comment by msegzda** [comment] 2019-06-04 12:55
Pitty this is enabled with advanced on-premise service which requires extra monthly fee

**Comment by rudpot** [comment] 2019-10-09 01:06
I am still seeing this problem. Set up a raspberry pi with current raspbian (debian release 10.1), installed ssm agent (2.3.714.0-1), create hybrid activation, finished activation procedure successfully, managed instance shows as "online". 

Using "start session" action from console generates a red "An unknown error occurred" banner.   

Using the cli   generates "BadRequest" with no additional information

```
# aws ssm start-session --target mi-0e94eaae27bc99c65

An error occurred (BadRequest) when calling the StartSession operation: 
```

**Comment by rudpot** [comment] 2019-10-09 01:25
> I am still seeing this problem. Set up a raspberry pi with current raspbian (debian release 10.1), installed ssm agent (2.3.714.0-1), create hybrid activation, finished activation procedure successfully, managed instance shows as "online".
> 
> Using "start session" action from console generates a red "An unknown error occurred" banner.
> 
> Using the cli generates "BadRequest" with no additional information
> 
> ```
> # aws ssm start-session --target mi-0e94eaae27bc99c65
> 
> An error occurred (BadRequest) when calling the StartSession operation: 
> ```

Nevermind - it actually works if one performs the "optional" step to [enable "advanced" features and pricing](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-managedinstances-advanced.html).

**Comment by ju187** [comment] 2020-01-10 01:04
Piggy back on this one. What exactly does it mean to "you must install and enable a certificate from Amazon Trust Services using AWS Certificate Manager (ACM). " for a on promise VM?  I assume it means a certificate is required if the vm is to communicate with AWS services.  Some examples will be helpful.

**Comment by lucheeseng827** [comment] 2020-01-31 08:14
I encounter such problem but when I troubleshoot it, it's caused by **wrong default region**(mine was pointing ap-northeast-1 but mi- was located in ap-southeast-1).

**Comment by rudpot** [comment] 2020-02-03 19:35
> Piggy back on this one. What exactly does it mean to "you must install and enable a certificate from Amazon Trust Services using AWS Certificate Manager (ACM). " for a on promise VM? I assume it means a certificate is required if the vm is to communicate with AWS services. Some examples will be helpful.

For the SSM agent to validate that it's actually talking to a legitimate  amazon endpoint it needs to have an Amazon Root Certificate installed in the system root certificates. As per this [stackexchange article](https://unix.stackexchange.com/questions/97244/list-all-available-ssl-ca-certificates), on a raspberry pi you can verify that they are installed like so:

```
awk -v cmd='openssl x509 -noout -subject' '
    /BEGIN/{close(cmd)};{print | cmd}' < /etc/ssl/certs/ca-certificates.crt \
| grep -i amazon
```

These are likely already installed by default but if not, just check how to install root certs on your system and grab the relevant root certs from amazontrust.com as described [here](https://docs.aws.amazon.com/iot/latest/developerguide/server-authentication.html#server-authentication-certs)

**Comment by altjx** [comment] 2020-11-16 22:49
@rudpot,

Any clue what the issue may be if certificates actually are installed on the target instance?

```
awk -v cmd='openssl x509 -noout -subject' '
    /BEGIN/{close(cmd)};{print | cmd}' < /etc/ssl/certs/ca-certificates.crt \
| grep -i amazon
subject=C = US, O = Amazon, CN = Amazon Root CA 1
subject=C = US, O = Amazon, CN = Amazon Root CA 2
subject=C = US, O = Amazon, CN = Amazon Root CA 3
subject=C = US, O = Amazon, CN = Amazon Root CA 4
```
