### ISSUE TITLE
change ssm-user group

### ISSUE THREAD

**Issue by HewittJC** [aws/amazon-ssm-agent#159] opened 2019-01-21 18:27 UTC
It seems that I am unable to change the groups that the SSM-User is in.

I need to be able to add this user to the Docker group so that our team members can login and accomplish tasks without being logged in as a root user. I do also understand that having access to the Docker group can end up leading to full root access any how if you really wanted to, but there are steps we can take to mitigate this.

**Comment by keirans** [comment] 2019-01-29 23:10
Hey There,

Duplicate of : https://github.com/aws/amazon-ssm-agent/issues/124

Might be worth checking that thread out.

K

**Closed** 2019-07-03 00:34 UTC
