### ISSUE TITLE
How to disable debug prints?

### ISSUE THREAD

**Issue by shayts7** [aws/amazon-ssm-agent#14] opened 2016-09-05 11:58 UTC
Hi,

I'm getting a very large debug print every ~20 sec.
When I look in the code I reach this function, and according to the code I can only guess that the aws.LogDebug is turned on in my env: https://github.com/aws/amazon-ssm-agent/blob/11049f2f75e0387f3fa432123c4eed52eaec812e/vendor/src/github.com/aws/aws-sdk-go/aws/client/client.go#L76

How can I find what is the Log Level in my env? and how can I change it?

I'm running the agent in a docker container using this command:
`
/bin/bash -a -c '/usr/bin/docker run \
--name ssm_agent \
-v /var/run/dbus:/var/run/dbus \
-v /run/systemd:/run/systemd \
-v /var/run/docker.sock:/var/run/docker.sock \
-v $(which docker):/usr/bin/docker \
-v /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02 \
rlister/amazon-ssm-agent:latest
`

Thanks,
Shay

**Comment by shihuazhang** [comment] 2016-09-06 22:05
Hi @shayts7,
The team is aware of the issue, we are working on the fixes.

**Comment by shayts7** [comment] 2016-09-07 07:19
@shihuazhang, thanks for the update

**Comment by shayts7** [comment] 2016-10-09 08:10
@shihuazhang - Any estimations for when the fix will be ready?

Thanks,
Shay

**Comment by shihuazhang** [comment] 2017-01-19 19:24
@shayts7 The issue is addressed in the latest build.

Free feel to reopen this if you have more question

**Closed by shihuazhang** 2017-01-19 19:24 UTC
