### ISSUE TITLE
double logging : amazon-ssm-agent.log and stdout messages

### ISSUE THREAD

**Issue by ashleyhull-versent** [aws/amazon-ssm-agent#66] opened 2017-08-22 05:35 UTC
Hi,

I don't want ssm logs to reach the messages. 
--
#tail amazon-ssm-agent.log
Aug 22 15:28:01 ip-10-32-4-10.ops-build.np-jhg.cloud amazon-ssm-agent[961]: 2017-08-22 15:28:01 INFO [instanceID=i-0808e545662ba8b83] [MessagingDeliveryService] [Association] Schedule manager refre... associated
Aug 22 15:31:12 ip-10-32-4-10.ops-build.np-jhg.cloud amazon-ssm-agent[961]: 2017-08-22 15:31:12 INFO [instanceID=i-0808e545662ba8b83] [HealthCheck] HealthCheck reporting agent health.

#messages
Aug 22 15:26:12 ip-172-31-12-13 amazon-ssm-agent: 2017-08-22 15:26:12 INFO [instanceID=i-0808e545662ba8b83] [HealthCheck] HealthCheck reporting agent health.
Aug 22 15:27:01 ip-172-31-12-13 systemd: Started Session 42 of user root.
Aug 22 15:27:01 ip-172-31-12-13 systemd: Starting Session 42 of user root.
Aug 22 15:28:01 ip-172-31-12-13 amazon-ssm-agent: 2017-08-22 15:28:01 INFO [instanceID=i-0808e545662ba8b83] [MessagingDeliveryService] [Association] Schedule manager refreshed with 0 associations, 0 new assocations associated

How do I stop ssm from logging to both locations?

**Comment by ashleyhull-versent** [comment] 2017-08-22 05:36
likely dupe of #59 59

**Comment by mmendonca3** [comment] 2018-02-05 20:01
Closing this issue since it is a duplicate of #59

**Closed by mmendonca3** 2018-02-05 20:01 UTC
