### ISSUE TITLE
SIGSEGV in SSM agent (v2.3.372.0)

### ISSUE THREAD

**Issue by uherberg** [aws/amazon-ssm-agent#163] opened 2019-01-26 00:29 UTC
When I start my new EC2 instance, the SSM agent works fine and I can start a session to the machine. However, after reboot, I get this error:

    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: panic: runtime error: invalid memory address or nil pointer dereference
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xaf9edd]
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: goroutine 1085 [running]:
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: github.com/aws/amazon-ssm-agent/agent/session/controlchannel.(*ControlChannel).SendMessage(0xc4200605f0, 0x135ab00, 0xc4200e1e60, 0xc420238000, 0x181, 0x181, 0x2, 0x1a, 0x0)
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: /local/p4clients/pkgbuild-eKkda/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/session/controlchannel/controlchannel.go:141 +0x2d
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: github.com/aws/amazon-ssm-agent/agent/session.(*Session).listenReply(0xc420436540, 0xc4200591a0, 0xc42001bb20, 0x13)
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: /local/p4clients/pkgbuild-eKkda/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/session/session.go:299 +0x347
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: created by github.com/aws/amazon-ssm-agent/agent/session.(*Session).ModuleExecute
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: /local/p4clients/pkgbuild-eKkda/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/session/session.go:186 +0x2d6

I have set up HTTPS_PROXY and no default route to a NAT. Here are the logs just before this SIGSEGV:

    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO Create new startup processor
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO [LongRunningPluginsManager] registered plugins: {}
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO Initializing bookkeeping folders
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO removing the completed state files
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO Initializing bookkeeping folders for long running plugins
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO Initializing replies folder for MDS reply requests that couldn't reach the service
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO Initializing healthcheck folders for long running plugins
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO Initializing locations for inventory plugin
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO Initializing default location for custom inventory
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO Initializing default location for file inventory
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO Initializing default location for role inventory
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO Init the cloudwatchlogs publisher
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO Starting Agent: amazon-ssm-agent - v2.3.372.0
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: 2019-01-26 00:11:02 INFO OS: linux, Arch: amd64
    Jan 26 00:11:02 ip-10-10-15-145 amazon-ssm-agent: datastore file /var/lib/amazon/ssm/i-00e1e1be4ac0cd653/longrunningplugins/datastore/store doesn't exist - no long running plugins to execute

**Comment by nitikagoyal87** [comment] 2019-02-05 19:21
Thanks for reaching out. We are unable to reproduce this issue and will need your help to provide us with below information to proceed with investigation:

- Are you able to reproduce this issue consistently?
- What EC2 instance OS type did you use?
- When instance went down for reboot, did you have any active sessions?
- Are you able to start a new session after reboot even though you see reported errors in agent log? If not, could you please restart your Amazon SSM Agent and see if this fixes your issue as a workaround until we root cause this issue.

**Comment by nitikagoyal87** [comment] 2019-02-15 23:31
We have identified potential root cause of this issue and currently working on the fix. Please note this issue cannot be reproduced consistently and occurs under a special scenario of one or more sessions being in active/connected status when instance is rebooted.

**Comment by nitikagoyal87** [comment] 2019-03-07 19:53
We have released a fix for this issue in version 2.3.479.0. Please let us know in case of further queries. Thanks!

**Closed** 2019-03-22 18:18 UTC
